version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: strapi_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
# http://localhost:1337/admin/auth/register-admin
